# Generated by Django 5.0.6 on 2024-06-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
