# Generated by Django 5.0.6 on 2024-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0005_alter_topic_modified_at_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_times',
            field=models.FloatField(null=True),
        ),
    ]
