# Generated by Django 5.0.6 on 2024-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0010_rename_units_userdefinedunits_alter_task_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='userdefinedunits',
            name='task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='system_defined_unit',
            field=models.CharField(choices=[('nos', 'nos'), ('hrs', 'hours'), ('kms', 'Kilometres')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
