# Generated by Django 5.0.6 on 2024-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0012_task_user_defined_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='system_defined_unit',
            field=models.CharField(blank=True, choices=[('nos', 'nos'), ('hrs', 'hours'), ('kms', 'Kilometres')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_defined_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
